# Generated by Django 5.2.6 on 2025-09-23 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_item_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomm.inventory'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
